env:
  browser: true
  es6: true
  node: true
extends:
  - '@ridedott/eslint-config'
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  unicorn/filename-case: 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/typedef': 'off'
  '@typescript-eslint/promise-function-async': 'off'
  'react/prop-types': 'off'
  'unicorn/prevent-abbreviations': 'off'
settings:
  react:
    version: 'detect'
